from enum import Enum


class CodeLanguage(Enum):
    """프로그래밍 언어를 나타내는 열거형"""
    JAVA17 = "JAVA17"
    NODEJS20 = "NODEJS20"
    NODEJS20ESM = "NODEJS20ESM"
    PYTHON3 = "PYTHON3"
    C11 = "C11"
    CPP17 = "CPP17"


class FailureCause(Enum):
    """채점 미통과 원인을 나타내는 열거형"""
    COMPILE_ERROR = "COMPILE_ERROR"
    COMPILE_TIMEOUT = "COMPILE_TIMEOUT"
    COMPILE_OUT_OF_MEMORY = "COMPILE_OUT_OF_MEMORY"

    RUNTIME_ERROR = "RUNTIME_ERROR"
    RUNTIME_TIMEOUT = "RUNTIME_TIMEOUT"
    RUNTIME_OUT_OF_MEMORY = "RUNTIME_OUT_OF_MEMORY"

    WRONG_ANSWER = "WRONG_ANSWER"

    SANDBOX_TIMEOUT = "SANDBOX_TIMEOUT"
    SANDBOX_OUT_OF_MEMORY = "SANDBOX_OUT_OF_MEMORY"